### ISSUE TITLE
A problem about loading model

### ISSUE THREAD

**Issue by ksw9446** [danielgordon10/thor-iqa-cvpr-2018#1] opened 2018-07-10 13:44 UTC
Hi, thanks for your codes sharing.

I set up environment along requirements to run your code.
Then, I tried to run "train.py", but I got some error message.
```
train rl agent
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 max          2 x 2 / 2   608 x 608 x  32   ->   304 x 304 x  32
    2 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    3 max          2 x 2 / 2   304 x 304 x  64   ->   152 x 152 x  64
    4 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    5 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    6 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    7 max          2 x 2 / 2   152 x 152 x 128   ->    76 x  76 x 128
    8 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
    9 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
   10 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
   11 max          2 x 2 / 2    76 x  76 x 256   ->    38 x  38 x 256
   12 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512  3.407 BFLOPs
   13 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256  0.379 BFLOPs
   14 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512  3.407 BFLOPs
   15 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256  0.379 BFLOPs
   16 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512  3.407 BFLOPs
   17 max          2 x 2 / 2    38 x  38 x 512   ->    19 x  19 x 512
   18 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024  3.407 BFLOPs
   19 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512  0.379 BFLOPs
   20 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024  3.407 BFLOPs
   21 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512  0.379 BFLOPs
   22 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024  3.407 BFLOPs
   23 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512  0.379 BFLOPs
   24 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024  3.407 BFLOPs
   25 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512  0.379 BFLOPs
   26 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024  3.407 BFLOPs
   27 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512  0.379 BFLOPs
   28 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024  3.407 BFLOPs
   29 conv    186  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 186  0.138 BFLOPs
   30 detection
python: ./src/parser.c:348: parse_region: Assertion `l.outputs == params.inputs' failed.
Aborted (core dumped)
```

'end_to_end_baseline' task show same error.
Could you please help me?

Thanks.

**Comment by danielgordon10** [comment] 2018-07-17 22:33
That looks like an issue with the Darknet Object Detector. Are you able to get https://github.com/danielgordon10/thor-iqa-cvpr-2018/blob/master/darknet_object_detection/detector.py running? If you put some sample images in a test folder, it should output the detections over it.

**Comment by ksw9446** [comment] 2018-08-02 04:27
I tried to run detector.py.
But, same error was appeared.
```
self.net = dn.load_net(py_util.encode(WEIGHT_PATH + 'yolov3-thor.cfg'),
                       py_util.encode(WEIGHT_PATH + 'yolov3-thor_final.weights'), 0)
```
this code made error.

It looks like unmatching between 'cfg' and 'weights'.
When I tested basic yolo3 in yolo3 page, it ran well.
Please help me to run code.

**Comment by danielgordon10** [comment] 2018-08-08 22:12
Try to download the new weights file. It should be fixed.

**Closed** 2018-08-14 17:00 UTC

**Comment by lkhazyf** [comment] 2021-05-23 04:22
@danielgordon10 Thanks for your excellent work. However, I also have this problem. Could you tell me where to download the new weights file? Thanks again.

**Comment by danielgordon10** [comment] 2021-05-25 00:12
```sh
pip install -r requirements.txt
sh download_weights.sh
```

**Comment by lkhazyf** [comment] 2021-05-25 00:26
Dear gordon, actually, this is what I did. And I got "floating point exception(core dump)". The wrong codes are 
self.net = dn.load_net(py_util.encode(WEIGHT_PATH + 'yolov3-thor.cfg'),
                       py_util.encode(WEIGHT_PATH + 'yolov3-thor_final.weights'), 0)


If I annotate this，I got ‘could not open file: thor.names’. I really want to reproduce this paper. Could you please help me? Thanks very much.

**Comment by danielgordon10** [comment] 2021-05-25 18:40
Sounds like the issue is actually with the Darknet codebase. Maybe your issue would be better helped there.

**Comment by lkhazyf** [comment] 2021-05-26 00:56
Thanks for your reply. I will try the Darknet. Have a nice day. (*￣︶￣)
